# Generated by Django 3.0.3 on 2020-03-14 17:05

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Contest',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
            ],
        ),
        migrations.CreateModel(
            name='CustomUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ratings', models.IntegerField()),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Problem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('statement', models.TextField()),
                ('memory_limit', models.IntegerField()),
                ('time_limit', models.IntegerField()),
                ('time_duration', models.IntegerField()),
                ('hardness', models.CharField(choices=[('Easy', 'Easy'), ('Medium', 'Medium'), ('Hard', 'Hard')], default='Easy', max_length=7)),
                ('points', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codefighter.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='TestCase',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('input', models.FileField(upload_to='')),
                ('output', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Submission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verdict', models.CharField(choices=[('AC', 'AC'), ('WA', 'WA'), ('TLE', 'TLE')], default='WA', max_length=10)),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codefighter.Contest')),
                ('problem', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codefighter.Problem')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codefighter.CustomUser')),
            ],
        ),
        migrations.CreateModel(
            name='Ranklist',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contest', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='codefighter.Contest')),
            ],
        ),
        migrations.AddField(
            model_name='problem',
            name='testcase',
            field=models.ManyToManyField(to='codefighter.TestCase'),
        ),
        migrations.AddField(
            model_name='contest',
            name='problem_list',
            field=models.ManyToManyField(to='codefighter.Problem'),
        ),
        migrations.AddField(
            model_name='contest',
            name='user_list',
            field=models.ManyToManyField(to='codefighter.CustomUser'),
        ),
    ]
